-- GlucoTrack download counter schema
-- Run this in Supabase Dashboard -> SQL Editor

create table if not exists public.downloads (
  id int primary key,
  count bigint not null default 0
);

insert into public.downloads (id, count)
values (1, 0)
on conflict (id) do nothing;

-- Optional hardening: enable RLS so anon/public cannot modify
alter table public.downloads enable row level security;

-- Atomic increment used by Netlify Function GET /download
create or replace function public.increment_downloads()
returns void
language sql
as $$
  update public.downloads set count = count + 1 where id = 1;
$$;

-- Transaction log: one row per download event (for “real transaction” proof)
create table if not exists public.download_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_agent text,
  referrer text
);

alter table public.download_events enable row level security;

-- Atomic increment + event insert. Returns the new event id (transaction id).
create or replace function public.increment_downloads_and_log(p_user_agent text, p_referrer text)
returns bigint
language sql
as $$
  with inc as (
    update public.downloads set count = count + 1 where id = 1
  ), ins as (
    insert into public.download_events (user_agent, referrer)
    values (p_user_agent, p_referrer)
    returning id
  )
  select id from ins;
$$;

-- Manual payment proofs (for EasyPaisa demo without merchant API credentials)
create table if not exists public.payment_proofs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  provider text not null default 'easypaisa',
  transaction_id text not null,
  amount_pkr int not null,
  note text
);

create unique index if not exists payment_proofs_provider_txn_unique
on public.payment_proofs(provider, transaction_id);

alter table public.payment_proofs enable row level security;
