-- Seed one real EasyPaisa payment proof row (committee demo)
-- Note: This stores ONLY transaction id + amount + timestamp.

-- If you haven't run supabase/schema.sql yet, this creates the required table.
create table if not exists public.payment_proofs (
	id bigint generated by default as identity primary key,
	created_at timestamptz not null default now(),
	provider text not null default 'easypaisa',
	transaction_id text not null,
	amount_pkr int not null,
	note text
);

create unique index if not exists payment_proofs_provider_txn_unique
on public.payment_proofs(provider, transaction_id);

alter table public.payment_proofs enable row level security;

insert into public.payment_proofs (provider, transaction_id, amount_pkr)
values ('easypaisa', '46020613208', 1350)
on conflict (provider, transaction_id) do nothing;
